# Generated by Django 4.1.6 on 2023-02-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='movies',
            name='producer',
            field=models.CharField(max_length=128),
        ),
    ]
