# Generated by Django 4.1.6 on 2023-02-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlainText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_text', models.CharField(max_length=200)),
                ('input_date', models.DateTimeField(verbose_name='Date and Time of Input')),
            ],
        ),
    ]
