# Generated by Django 4.1.6 on 2023-02-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex02', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlainText',
        ),
    ]
